// Moves: type, category, power, accuracy, PP and effects — the turn-based battle and
// the real-time companion both read these.
// cat: 'phys' | 'spec' | 'status'. acc: 0 = never misses.
// fx: status ('brn','par','psn','tox','slp','frz','conf') with chance; stat stages on
// foe/self; heal (fraction of max), drain, recoil, multi [min,max], flinch, crit,
// prio, fixed ('level' or a number), recharge, selfKO, rest, money, splash.

const M = (name, type, cat, power, acc, pp, fx = {}) => ({ name, type, cat, power, acc, pp, fx });

export const MOVES = {
  // Normal
  tackle: M('Tackle', 'normal', 'phys', 40, 100, 35),
  scratch: M('Scratch', 'normal', 'phys', 40, 100, 35),
  pound: M('Pound', 'normal', 'phys', 40, 100, 35),
  quickAttack: M('Quick Attack', 'normal', 'phys', 40, 100, 30, { prio: 1 }),
  extremeSpeed: M('Extreme Speed', 'normal', 'phys', 80, 100, 5, { prio: 2 }),
  headbutt: M('Headbutt', 'normal', 'phys', 70, 100, 15, { flinch: 0.3 }),
  bodySlam: M('Body Slam', 'normal', 'phys', 85, 100, 15, { status: 'par', chance: 0.3 }),
  slam: M('Slam', 'normal', 'phys', 80, 75, 20),
  takeDown: M('Take Down', 'normal', 'phys', 90, 85, 20, { recoil: 0.25 }),
  doubleEdge: M('Double-Edge', 'normal', 'phys', 120, 100, 15, { recoil: 0.33 }),
  hyperFang: M('Hyper Fang', 'normal', 'phys', 80, 90, 15, { flinch: 0.1 }),
  furySwipes: M('Fury Swipes', 'normal', 'phys', 18, 80, 15, { multi: [2, 5] }),
  megaPunch: M('Mega Punch', 'normal', 'phys', 80, 85, 20),
  returnMove: M('Return', 'normal', 'phys', 102, 100, 20),
  hyperBeam: M('Hyper Beam', 'normal', 'spec', 150, 90, 5, { recharge: true }),
  swift: M('Swift', 'normal', 'spec', 60, 0, 20),
  triAttack: M('Tri Attack', 'normal', 'spec', 80, 100, 10, { status: 'par', chance: 0.2 }),
  hyperVoice: M('Hyper Voice', 'normal', 'spec', 90, 100, 10),
  payDay: M('Pay Day', 'normal', 'phys', 40, 100, 20, { money: true }),
  selfDestruct: M('Self-Destruct', 'normal', 'phys', 200, 100, 5, { selfKO: true }),
  explosion: M('Explosion', 'normal', 'phys', 250, 100, 5, { selfKO: true }),
  growl: M('Growl', 'normal', 'status', 0, 100, 40, { foe: { atk: -1 } }),
  tailWhip: M('Tail Whip', 'normal', 'status', 0, 100, 30, { foe: { def: -1 } }),
  leer: M('Leer', 'normal', 'status', 0, 100, 30, { foe: { def: -1 } }),
  swordsDance: M('Swords Dance', 'normal', 'status', 0, 0, 20, { self: { atk: 2 } }),
  defenseCurl: M('Defense Curl', 'normal', 'status', 0, 0, 40, { self: { def: 1 } }),
  harden: M('Harden', 'normal', 'status', 0, 0, 30, { self: { def: 1 } }),
  sing: M('Sing', 'normal', 'status', 0, 55, 15, { status: 'slp', chance: 1 }),
  recover: M('Recover', 'normal', 'status', 0, 0, 10, { heal: 0.5 }),
  rest: M('Rest', 'psychic', 'status', 0, 0, 10, { rest: true }),
  splash: M('Splash', 'normal', 'status', 0, 0, 40, { splash: true }),
  // Fire
  ember: M('Ember', 'fire', 'spec', 40, 100, 25, { status: 'brn', chance: 0.1 }),
  flameWheel: M('Flame Wheel', 'fire', 'phys', 60, 100, 25, { status: 'brn', chance: 0.1 }),
  fireFang: M('Fire Fang', 'fire', 'phys', 65, 95, 15, { status: 'brn', chance: 0.1, flinch: 0.1 }),
  flamethrower: M('Flamethrower', 'fire', 'spec', 90, 100, 15, { status: 'brn', chance: 0.1 }),
  fireBlast: M('Fire Blast', 'fire', 'spec', 110, 85, 5, { status: 'brn', chance: 0.1 }),
  flareBlitz: M('Flare Blitz', 'fire', 'phys', 120, 100, 15, { recoil: 0.33, status: 'brn', chance: 0.1 }),
  fireSpin: M('Fire Spin', 'fire', 'spec', 35, 85, 15),
  willOWisp: M('Will-O-Wisp', 'fire', 'status', 0, 85, 15, { status: 'brn', chance: 1 }),
  // Water
  waterGun: M('Water Gun', 'water', 'spec', 40, 100, 25),
  bubble: M('Bubble', 'water', 'spec', 40, 100, 30, { foe: { spe: -1 }, chance: 0.1 }),
  bubbleBeam: M('Bubble Beam', 'water', 'spec', 65, 100, 20, { foe: { spe: -1 }, chance: 0.1 }),
  waterPulse: M('Water Pulse', 'water', 'spec', 60, 100, 20, { status: 'conf', chance: 0.2 }),
  surf: M('Surf', 'water', 'spec', 90, 100, 15),
  hydroPump: M('Hydro Pump', 'water', 'spec', 110, 80, 5),
  scald: M('Scald', 'water', 'spec', 80, 100, 15, { status: 'brn', chance: 0.3 }),
  aquaTail: M('Aqua Tail', 'water', 'phys', 90, 90, 10),
  waterfall: M('Waterfall', 'water', 'phys', 80, 100, 15, { flinch: 0.2 }),
  withdraw: M('Withdraw', 'water', 'status', 0, 0, 40, { self: { def: 1 } }),
  // Electric
  thunderShock: M('Thunder Shock', 'electric', 'spec', 40, 100, 30, { status: 'par', chance: 0.1 }),
  spark: M('Spark', 'electric', 'phys', 65, 100, 20, { status: 'par', chance: 0.3 }),
  thunderbolt: M('Thunderbolt', 'electric', 'spec', 90, 100, 15, { status: 'par', chance: 0.1 }),
  discharge: M('Discharge', 'electric', 'spec', 80, 100, 15, { status: 'par', chance: 0.3 }),
  thunder: M('Thunder', 'electric', 'spec', 110, 70, 10, { status: 'par', chance: 0.3 }),
  voltTackle: M('Volt Tackle', 'electric', 'phys', 120, 100, 15, { recoil: 0.33, status: 'par', chance: 0.1 }),
  thunderWave: M('Thunder Wave', 'electric', 'status', 0, 90, 20, { status: 'par', chance: 1 }),
  // Grass
  vineWhip: M('Vine Whip', 'grass', 'phys', 45, 100, 25),
  razorLeaf: M('Razor Leaf', 'grass', 'phys', 55, 95, 25, { crit: true }),
  absorb: M('Absorb', 'grass', 'spec', 20, 100, 25, { drain: 0.5 }),
  megaDrain: M('Mega Drain', 'grass', 'spec', 40, 100, 15, { drain: 0.5 }),
  gigaDrain: M('Giga Drain', 'grass', 'spec', 75, 100, 10, { drain: 0.5 }),
  seedBomb: M('Seed Bomb', 'grass', 'phys', 80, 100, 15),
  leafBlade: M('Leaf Blade', 'grass', 'phys', 90, 100, 15, { crit: true }),
  energyBall: M('Energy Ball', 'grass', 'spec', 90, 100, 10),
  petalDance: M('Petal Dance', 'grass', 'spec', 120, 100, 10),
  solarBeam: M('Solar Beam', 'grass', 'spec', 120, 100, 10),
  sleepPowder: M('Sleep Powder', 'grass', 'status', 0, 75, 15, { status: 'slp', chance: 1 }),
  stunSpore: M('Stun Spore', 'grass', 'status', 0, 75, 30, { status: 'par', chance: 1 }),
  poisonPowder: M('Poison Powder', 'poison', 'status', 0, 75, 35, { status: 'psn', chance: 1 }),
  synthesis: M('Synthesis', 'grass', 'status', 0, 0, 5, { heal: 0.5 }),
  // Ice
  powderSnow: M('Powder Snow', 'ice', 'spec', 40, 100, 25, { status: 'frz', chance: 0.1 }),
  iceShard: M('Ice Shard', 'ice', 'phys', 40, 100, 30, { prio: 1 }),
  iceFang: M('Ice Fang', 'ice', 'phys', 65, 95, 15, { status: 'frz', chance: 0.1, flinch: 0.1 }),
  auroraBeam: M('Aurora Beam', 'ice', 'spec', 65, 100, 20, { foe: { atk: -1 }, chance: 0.1 }),
  iceBeam: M('Ice Beam', 'ice', 'spec', 90, 100, 10, { status: 'frz', chance: 0.1 }),
  blizzard: M('Blizzard', 'ice', 'spec', 110, 70, 5, { status: 'frz', chance: 0.1 }),
  // Fighting
  karateChop: M('Karate Chop', 'fighting', 'phys', 50, 100, 25, { crit: true }),
  machPunch: M('Mach Punch', 'fighting', 'phys', 40, 100, 30, { prio: 1 }),
  doubleKick: M('Double Kick', 'fighting', 'phys', 30, 100, 30, { multi: [2, 2] }),
  lowKick: M('Low Kick', 'fighting', 'phys', 65, 100, 20),
  forcePalm: M('Force Palm', 'fighting', 'phys', 60, 100, 10, { status: 'par', chance: 0.3 }),
  brickBreak: M('Brick Break', 'fighting', 'phys', 75, 100, 15),
  submission: M('Submission', 'fighting', 'phys', 80, 80, 20, { recoil: 0.25 }),
  seismicToss: M('Seismic Toss', 'fighting', 'phys', 1, 100, 20, { fixed: 'level' }),
  crossChop: M('Cross Chop', 'fighting', 'phys', 100, 80, 5, { crit: true }),
  closeCombat: M('Close Combat', 'fighting', 'phys', 120, 100, 5, { self: { def: -1 } }),
  auraSphere: M('Aura Sphere', 'fighting', 'spec', 80, 0, 20),
  bulkUp: M('Bulk Up', 'fighting', 'status', 0, 0, 20, { self: { atk: 1, def: 1 } }),
  // Poison
  poisonSting: M('Poison Sting', 'poison', 'phys', 15, 100, 35, { status: 'psn', chance: 0.3 }),
  smog: M('Smog', 'poison', 'spec', 30, 70, 20, { status: 'psn', chance: 0.4 }),
  acid: M('Acid', 'poison', 'spec', 40, 100, 30, { foe: { spd: -1 }, chance: 0.1 }),
  poisonFang: M('Poison Fang', 'poison', 'phys', 50, 100, 15, { status: 'tox', chance: 0.5 }),
  sludge: M('Sludge', 'poison', 'spec', 65, 100, 20, { status: 'psn', chance: 0.3 }),
  poisonJab: M('Poison Jab', 'poison', 'phys', 80, 100, 20, { status: 'psn', chance: 0.3 }),
  sludgeBomb: M('Sludge Bomb', 'poison', 'spec', 90, 100, 10, { status: 'psn', chance: 0.3 }),
  toxic: M('Toxic', 'poison', 'status', 0, 90, 10, { status: 'tox', chance: 1 }),
  // Ground
  mudSlap: M('Mud-Slap', 'ground', 'spec', 20, 100, 10),
  mudShot: M('Mud Shot', 'ground', 'spec', 55, 95, 15, { foe: { spe: -1 }, chance: 1 }),
  boneClub: M('Bone Club', 'ground', 'phys', 65, 85, 20, { flinch: 0.1 }),
  bonemerang: M('Bonemerang', 'ground', 'phys', 50, 90, 10, { multi: [2, 2] }),
  dig: M('Dig', 'ground', 'phys', 80, 100, 10),
  earthPower: M('Earth Power', 'ground', 'spec', 90, 100, 10, { foe: { spd: -1 }, chance: 0.1 }),
  earthquake: M('Earthquake', 'ground', 'phys', 100, 100, 10),
  // Flying
  peck: M('Peck', 'flying', 'phys', 35, 100, 35),
  gust: M('Gust', 'flying', 'spec', 40, 100, 35),
  wingAttack: M('Wing Attack', 'flying', 'phys', 60, 100, 35),
  aerialAce: M('Aerial Ace', 'flying', 'phys', 60, 0, 20),
  airSlash: M('Air Slash', 'flying', 'spec', 75, 95, 15, { flinch: 0.3 }),
  drillPeck: M('Drill Peck', 'flying', 'phys', 80, 100, 20),
  fly: M('Fly', 'flying', 'phys', 90, 95, 15),
  braveBird: M('Brave Bird', 'flying', 'phys', 120, 100, 15, { recoil: 0.33 }),
  hurricane: M('Hurricane', 'flying', 'spec', 110, 70, 10, { status: 'conf', chance: 0.3 }),
  roost: M('Roost', 'flying', 'status', 0, 0, 10, { heal: 0.5 }),
  // Psychic
  confusion: M('Confusion', 'psychic', 'spec', 50, 100, 25, { status: 'conf', chance: 0.1 }),
  psybeam: M('Psybeam', 'psychic', 'spec', 65, 100, 20, { status: 'conf', chance: 0.1 }),
  psychoCut: M('Psycho Cut', 'psychic', 'phys', 70, 100, 20, { crit: true }),
  zenHeadbutt: M('Zen Headbutt', 'psychic', 'phys', 80, 90, 15, { flinch: 0.2 }),
  psychic: M('Psychic', 'psychic', 'spec', 90, 100, 10, { foe: { spd: -1 }, chance: 0.1 }),
  hypnosis: M('Hypnosis', 'psychic', 'status', 0, 60, 20, { status: 'slp', chance: 1 }),
  calmMind: M('Calm Mind', 'psychic', 'status', 0, 0, 20, { self: { spa: 1, spd: 1 } }),
  amnesia: M('Amnesia', 'psychic', 'status', 0, 0, 20, { self: { spd: 2 } }),
  // Bug
  stringShot: M('String Shot', 'bug', 'status', 0, 95, 40, { foe: { spe: -2 } }),
  bugBite: M('Bug Bite', 'bug', 'phys', 60, 100, 20),
  pinMissile: M('Pin Missile', 'bug', 'phys', 25, 95, 20, { multi: [2, 5] }),
  leechLife: M('Leech Life', 'bug', 'phys', 80, 100, 10, { drain: 0.5 }),
  signalBeam: M('Signal Beam', 'bug', 'spec', 75, 100, 15, { status: 'conf', chance: 0.1 }),
  xScissor: M('X-Scissor', 'bug', 'phys', 80, 100, 15),
  bugBuzz: M('Bug Buzz', 'bug', 'spec', 90, 100, 10, { foe: { spd: -1 }, chance: 0.1 }),
  // Rock
  rockThrow: M('Rock Throw', 'rock', 'phys', 50, 90, 15),
  rockTomb: M('Rock Tomb', 'rock', 'phys', 60, 95, 15, { foe: { spe: -1 }, chance: 1 }),
  ancientPower: M('Ancient Power', 'rock', 'spec', 60, 100, 5),
  rockSlide: M('Rock Slide', 'rock', 'phys', 75, 90, 10, { flinch: 0.3 }),
  stoneEdge: M('Stone Edge', 'rock', 'phys', 100, 80, 5, { crit: true }),
  // Ghost
  astonish: M('Astonish', 'ghost', 'phys', 30, 100, 15, { flinch: 0.3 }),
  lick: M('Lick', 'ghost', 'phys', 30, 100, 30, { status: 'par', chance: 0.3 }),
  shadowSneak: M('Shadow Sneak', 'ghost', 'phys', 40, 100, 30, { prio: 1 }),
  nightShade: M('Night Shade', 'ghost', 'spec', 1, 100, 15, { fixed: 'level' }),
  hex: M('Hex', 'ghost', 'spec', 65, 100, 10),
  shadowClaw: M('Shadow Claw', 'ghost', 'phys', 70, 100, 15, { crit: true }),
  shadowBall: M('Shadow Ball', 'ghost', 'spec', 80, 100, 15, { foe: { spd: -1 }, chance: 0.2 }),
  confuseRay: M('Confuse Ray', 'ghost', 'status', 0, 100, 10, { status: 'conf', chance: 1 }),
  // Dragon
  dragonRage: M('Dragon Rage', 'dragon', 'spec', 1, 100, 10, { fixed: 40 }),
  twister: M('Twister', 'dragon', 'spec', 40, 100, 20, { flinch: 0.2 }),
  dragonBreath: M('Dragon Breath', 'dragon', 'spec', 60, 100, 20, { status: 'par', chance: 0.3 }),
  dragonClaw: M('Dragon Claw', 'dragon', 'phys', 80, 100, 15),
  dragonPulse: M('Dragon Pulse', 'dragon', 'spec', 85, 100, 10),
  outrage: M('Outrage', 'dragon', 'phys', 120, 100, 10),
  dracoMeteor: M('Draco Meteor', 'dragon', 'spec', 130, 90, 5, { self: { spa: -2 } }),
  dragonDance: M('Dragon Dance', 'dragon', 'status', 0, 0, 20, { self: { atk: 1, spe: 1 } }),
  // Dark
  bite: M('Bite', 'dark', 'phys', 60, 100, 25, { flinch: 0.3 }),
  suckerPunch: M('Sucker Punch', 'dark', 'phys', 70, 100, 5, { prio: 1 }),
  nightSlash: M('Night Slash', 'dark', 'phys', 70, 100, 15, { crit: true }),
  crunch: M('Crunch', 'dark', 'phys', 80, 100, 15, { foe: { def: -1 }, chance: 0.2 }),
  darkPulse: M('Dark Pulse', 'dark', 'spec', 80, 100, 15, { flinch: 0.2 }),
  // Steel
  metalClaw: M('Metal Claw', 'steel', 'phys', 50, 95, 35, { self: { atk: 1 }, chance: 0.1 }),
  bulletPunch: M('Bullet Punch', 'steel', 'phys', 40, 100, 30, { prio: 1 }),
  ironHead: M('Iron Head', 'steel', 'phys', 80, 100, 15, { flinch: 0.3 }),
  flashCannon: M('Flash Cannon', 'steel', 'spec', 80, 100, 10, { foe: { spd: -1 }, chance: 0.1 }),
  meteorMash: M('Meteor Mash', 'steel', 'phys', 90, 90, 10, { self: { atk: 1 }, chance: 0.2 }),
  ironTail: M('Iron Tail', 'steel', 'phys', 100, 75, 15, { foe: { def: -1 }, chance: 0.3 }),
  ironDefense: M('Iron Defense', 'steel', 'status', 0, 0, 15, { self: { def: 2 } }),
  // Fairy
  fairyWind: M('Fairy Wind', 'fairy', 'spec', 40, 100, 30),
  disarmingVoice: M('Disarming Voice', 'fairy', 'spec', 40, 0, 15),
  drainingKiss: M('Draining Kiss', 'fairy', 'spec', 50, 100, 10, { drain: 0.75 }),
  dazzlingGleam: M('Dazzling Gleam', 'fairy', 'spec', 80, 100, 10),
  playRough: M('Play Rough', 'fairy', 'phys', 90, 90, 10, { foe: { atk: -1 }, chance: 0.1 }),
  moonblast: M('Moonblast', 'fairy', 'spec', 95, 100, 15, { foe: { spa: -1 }, chance: 0.3 }),
  charm: M('Charm', 'fairy', 'status', 0, 100, 20, { foe: { atk: -2 } }),
  sweetKiss: M('Sweet Kiss', 'fairy', 'status', 0, 75, 10, { status: 'conf', chance: 1 }),
};
export const MOVE_IDS = Object.keys(MOVES);
